export { default as youTube } from "./youtube.svg";
export { default as oneOnethirdTwothird } from "./1_1-3_2-3.png";
export { default as oneOnethird } from "./1_1-3.png";
export { default as oneOne } from "./1_1.png";
export { default as oneTwoThree } from "./1_2_3.png";
export { default as oneTwothirdOnethird } from "./1_2-3_1-3.png";
export { default as oneTwothird } from "./1_2-3.png";
export { default as oneTwo } from "./1_2.png";
export { default as oneThree } from "./1_3.png";
export { default as onethirdOnethird } from "./1-3_1-3.png";
export { default as onethirdOne } from "./1-3_1.png";
export { default as onethirdTwothird } from "./1-3_2-3.png";
export { default as twoOne } from "./2_1.png";
export { default as twoTwo } from "./2_2.png";
export { default as twoThree} from "./2_3.png";
export { default as twothirdOne} from "./2-3_1.png";
export { default as twothirdTwothird} from "./2-3_2-3.png";
export { default as threeOne} from "./3_1.png";
export { default as threeTwo} from "./3_2.png";
export { default as threeThree} from "./3_3.png";
